# Generated by Django 4.1.8 on 2025-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='value_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'text'), (2, 'number'), (3, 'date'), (4, 'datetime'), (5, 'time'), (6, 'files'), (7, 'boolean'), (8, 'images')], default=0, help_text='value type', verbose_name='数值类型'),
        ),
    ]
