# Generated by Django 5.1.6 on 2025-03-13 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WXUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='crate time', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, help_text='delete time', null=True, verbose_name='删除时间')),
                ('applet_openid', models.CharField(blank=True, db_index=True, help_text='mini program openid', max_length=150, null=True, verbose_name='小程序openid')),
                ('official_account_openid', models.CharField(blank=True, db_index=True, help_text='official account openid', max_length=150, null=True, verbose_name='公众号openid')),
                ('video_account_openid', models.CharField(blank=True, db_index=True, help_text='video account openid', max_length=150, null=True, verbose_name='视频号openid')),
                ('unionid', models.CharField(blank=True, db_index=True, help_text='unionid', max_length=150, null=True, verbose_name='联合号')),
                ('session_key', models.CharField(blank=True, help_text='session key', max_length=255, null=True, verbose_name='后台认证key')),
                ('applet_access_token', models.CharField(blank=True, help_text='applet access token', max_length=255, null=True, verbose_name='小程序access_token')),
                ('applet_refresh_token', models.CharField(blank=True, help_text='applet refresh token', max_length=255, null=True, verbose_name='小程序refresh_token')),
                ('official_account_access_token', models.CharField(blank=True, help_text='official account access token', max_length=255, null=True, verbose_name='公众号access_token')),
                ('official_account_refresh_token', models.CharField(blank=True, help_text='official account refresh token', max_length=255, null=True, verbose_name='公众号refresh_token')),
                ('official_account_scope', models.CharField(blank=True, help_text='official account scope', max_length=255, null=True, verbose_name='公众号scope')),
                ('nickname', models.CharField(blank=True, help_text='nick name', max_length=150, null=True, verbose_name='昵称')),
                ('language', models.CharField(blank=True, help_text='language', max_length=40, null=True, verbose_name='语言')),
                ('sex', models.CharField(blank=True, help_text='sex', max_length=100, null=True, verbose_name='性别')),
                ('country', models.CharField(blank=True, help_text='country', max_length=100, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, help_text='province', max_length=100, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, help_text='city', max_length=100, null=True, verbose_name='市')),
                ('avatar_url', models.CharField(blank=True, help_text='avatar url', max_length=900, null=True, verbose_name='用户头像')),
                ('privilege', models.JSONField(blank=True, help_text='privilege', null=True, verbose_name='用户特权信息')),
                ('mobile', models.CharField(default='', help_text='mobile', max_length=150, verbose_name='微信小程序绑定的手机号码（国外手机号会有区号）')),
                ('user', models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信用户数据',
                'verbose_name_plural': '微信用户数据',
                'db_table': 'rj_wx_users',
            },
        ),
    ]
