# Generated by Django 5.1.6 on 2025-03-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='crate time', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, help_text='delete time', null=True, verbose_name='删除时间')),
                ('applet_openid', models.CharField(blank=True, db_index=True, help_text='mini program openid', max_length=150, null=True, verbose_name='小程序openid')),
                ('unionid', models.CharField(blank=True, db_index=True, help_text='unionid', max_length=150, null=True, verbose_name='联合号')),
                ('session_key', models.CharField(blank=True, help_text='session key', max_length=255, null=True, verbose_name='后台认证key')),
                ('applet_access_token', models.CharField(blank=True, help_text='applet access token', max_length=255, null=True, verbose_name='小程序access_token')),
                ('applet_refresh_token', models.CharField(blank=True, help_text='applet refresh token', max_length=255, null=True, verbose_name='小程序refresh_token')),
                ('nickname', models.CharField(blank=True, help_text='nick name', max_length=150, null=True, verbose_name='昵称')),
                ('language', models.CharField(blank=True, help_text='language', max_length=40, null=True, verbose_name='语言')),
                ('gender', models.CharField(blank=True, help_text='gender', max_length=100, null=True, verbose_name='性别')),
                ('country', models.CharField(blank=True, help_text='country', max_length=100, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, help_text='province', max_length=100, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, help_text='city', max_length=100, null=True, verbose_name='市')),
                ('avatar_url', models.CharField(blank=True, help_text='avatar url', max_length=900, null=True, verbose_name='用户头像')),
                ('privilege', models.JSONField(blank=True, help_text='privilege', null=True, verbose_name='用户特权信息')),
                ('mobile', models.CharField(default='', help_text='mobile', max_length=150, verbose_name='抖音小程序绑定的手机号码')),
            ],
            options={
                'verbose_name': '抖音用户数据',
                'verbose_name_plural': '抖音用户数据',
                'db_table': 'rj_tiktok_users',
            },
        ),
    ]
