# Generated by Django 5.1.6 on 2025-03-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(blank=True, help_text='parent code', max_length=64, null=True, verbose_name='父级城市编码')),
                ('code', models.CharField(blank=True, db_index=True, help_text='code', max_length=64, null=True, verbose_name='城市编码')),
                ('name', models.CharField(help_text='name', max_length=150, verbose_name='名称')),
                ('pinyin', models.CharField(blank=True, help_text='pinyin', max_length=255, null=True, verbose_name='拼音')),
                ('initials', models.CharField(blank=True, help_text='initials', max_length=20, null=True, verbose_name='首字母')),
                ('level', models.PositiveIntegerField(default=0, help_text='level', verbose_name='级别')),
                ('category', models.PositiveIntegerField(default=0, help_text='category', verbose_name='城乡分类')),
                ('status', models.SmallIntegerField(default=1, help_text='status', verbose_name='状态')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='region.region', verbose_name='上级行政区')),
            ],
            options={
                'verbose_name': '中国省市区',
                'verbose_name_plural': '中国省市区',
                'db_table': 'rj_region',
            },
        ),
    ]
