# Generated by Django 4.1.8 on 2025-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='crate time', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, help_text='delete time', null=True, verbose_name='删除时间')),
                ('label', models.CharField(blank=True, help_text='label', max_length=150, null=True, verbose_name='名称/标识')),
                ('code', models.CharField(blank=True, help_text='code', max_length=150, null=True, unique=True, verbose_name='代号')),
                ('value', models.CharField(blank=True, help_text='value', max_length=255, null=True, verbose_name='实际值')),
                ('description', models.CharField(blank=True, help_text='description', max_length=255, null=True, verbose_name='描述')),
                ('is_value', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, help_text='is value', verbose_name='是否为value值')),
                ('value_type', models.IntegerField(choices=[(0, 'text'), (1, 'number'), (2, 'date'), (3, 'datetime'), (4, 'time'), (5, 'files'), (6, 'boolean'), (7, 'images')], default=0, help_text='value type', verbose_name='数值类型')),
                ('color', models.CharField(blank=True, help_text='show color', max_length=150, null=True, verbose_name='颜色')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, help_text='status', verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='sort', null=True, verbose_name='显示排序')),
                ('remark', models.CharField(blank=True, help_text='remark', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '字典表',
                'verbose_name_plural': '字典表',
                'db_table': 'rj_dictionary',
                'ordering': ('sort',),
            },
        ),
    ]
